spring.application.name=vivaeventos-payment-service
server.port=${SERVER_PORT:8084}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/payment-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

services.order-service.url=${SERVICES_ORDER_SERVICE_URL:http://localhost:8083}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

vivaeventos.messaging.exchange=vivaeventos.events
vivaeventos.messaging.routing-key.approved=pago.aprobado
vivaeventos.messaging.routing-key.failed=pago.fallido

wompi.base-url=${WOMPI_BASE_URL:https://sandbox.wompi.co/v1}
wompi.private-key=${WOMPI_PRIVATE_KEY:}
wompi.public-key=${WOMPI_PUBLIC_KEY:}
wompi.redirect-url=${WOMPI_REDIRECT_URL:http://localhost:3000/payment/result}
wompi.callback-url=${WOMPI_CALLBACK_URL:http://localhost:8084/api/v1/payments/callback/wompi}

payment.gateway.provider=sandbox
