spring.application.name=vivaeventos-payment-service
server.port=${SERVER_PORT:8084}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/payment-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

services.order-service.url=${SERVICES_ORDER_SERVICE_URL:http://localhost:8083}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

vivaeventos.messaging.exchange=vivaeventos.events
vivaeventos.messaging.routing-key.approved=pago.aprobado
vivaeventos.messaging.routing-key.failed=pago.fallido

payment.gateway.provider=${PAYMENT_GATEWAY_PROVIDER:stripe}

stripe.secret-key=${STRIPE_SECRET_KEY:}
stripe.publishable-key=${STRIPE_PUBLISHABLE_KEY:}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:}
stripe.success-url=${STRIPE_SUCCESS_URL:http://localhost:8084/api/v1/payments/callback/success?session_id={CHECKOUT_SESSION_ID}}
stripe.cancel-url=${STRIPE_CANCEL_URL:http://localhost:8084/api/v1/payments/callback/cancel}
stripe.return-url=${STRIPE_RETURN_URL:http://localhost:3000/payment/success?session_id={CHECKOUT_SESSION_ID}}
stripe.cancel-return-url=${STRIPE_CANCEL_RETURN_URL:http://localhost:3000/payment/cancel}
stripe.api-base=${STRIPE_API_BASE:}
